# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: siphon_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'siphon_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14siphon_service.proto\x12\x0esiphon_service\")\n\x10GetSiphonRequest\x12\x15\n\rattributeName\x18\x01 \x01(\t\"\x81\x01\n\x11GetSiphonResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\tint_value\x18\x03 \x01(\x05H\x00\x12\x15\n\x0b\x66loat_value\x18\x04 \x01(\x02H\x00\x12\x15\n\x0b\x61rray_value\x18\x05 \x01(\x0cH\x00\x42\x07\n\x05value\"u\n\x10SetSiphonRequest\x12\x15\n\rattributeName\x18\x01 \x01(\t\x12\x13\n\tint_value\x18\x02 \x01(\x05H\x00\x12\x15\n\x0b\x66loat_value\x18\x03 \x01(\x02H\x00\x12\x15\n\x0b\x61rray_value\x18\x04 \x01(\x0cH\x00\x42\x07\n\x05value\"5\n\x11SetSiphonResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"-\n\x0fInputKeyRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"4\n\x10InputKeyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x15\n\x13\x43\x61ptureFrameRequest\"f\n\x14\x43\x61ptureFrameResponse\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\x0f\n\x07message\x18\x05 \x01(\t2\xe3\x02\n\rSiphonService\x12S\n\x0cGetAttribute\x12 .siphon_service.GetSiphonRequest\x1a!.siphon_service.GetSiphonResponse\x12S\n\x0cSetAttribute\x12 .siphon_service.SetSiphonRequest\x1a!.siphon_service.SetSiphonResponse\x12M\n\x08InputKey\x12\x1f.siphon_service.InputKeyRequest\x1a .siphon_service.InputKeyResponse\x12Y\n\x0c\x43\x61ptureFrame\x12#.siphon_service.CaptureFrameRequest\x1a$.siphon_service.CaptureFrameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'siphon_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSIPHONREQUEST']._serialized_start=40
  _globals['_GETSIPHONREQUEST']._serialized_end=81
  _globals['_GETSIPHONRESPONSE']._serialized_start=84
  _globals['_GETSIPHONRESPONSE']._serialized_end=213
  _globals['_SETSIPHONREQUEST']._serialized_start=215
  _globals['_SETSIPHONREQUEST']._serialized_end=332
  _globals['_SETSIPHONRESPONSE']._serialized_start=334
  _globals['_SETSIPHONRESPONSE']._serialized_end=387
  _globals['_INPUTKEYREQUEST']._serialized_start=389
  _globals['_INPUTKEYREQUEST']._serialized_end=434
  _globals['_INPUTKEYRESPONSE']._serialized_start=436
  _globals['_INPUTKEYRESPONSE']._serialized_end=488
  _globals['_CAPTUREFRAMEREQUEST']._serialized_start=490
  _globals['_CAPTUREFRAMEREQUEST']._serialized_end=511
  _globals['_CAPTUREFRAMERESPONSE']._serialized_start=513
  _globals['_CAPTUREFRAMERESPONSE']._serialized_end=615
  _globals['_SIPHONSERVICE']._serialized_start=618
  _globals['_SIPHONSERVICE']._serialized_end=973
# @@protoc_insertion_point(module_scope)
